import { test };

test('test', async ({ page }) => {
    await page.goto('https://stage_aithinkitive.uat.provider.ecarehealth.com/auth/login');
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('rose.gomez@jourrapide.com');
    await page.getByRole('textbox', { name: '*********' }).click();
    await page.getByRole('textbox', { name: '*********' }).fill('Pass@123');
    await page.getByRole('button', { name: 'Let\'s get Started' }).click();
    await page.getByRole('banner').getByTestId('KeyboardArrowRightIcon').click();
    await page.getByRole('tab', { name: 'Settings' }).click();
    await page.getByText('User Settings').click();
    await page.getByRole('tab', { name: 'Providers' }).click();
    await page.getByRole('button', { name: 'Add Provider User' }).click();
    await page.getByRole('textbox', { name: 'First Name *' }).click();
    await page.getByRole('textbox', { name: 'First Name *' }).fill('leonardo');
    await page.getByRole('textbox', { name: 'Last Name *' }).click();
    await page.getByRole('textbox', { name: 'Last Name *' }).fill('patel');
    await page.locator('div').filter({ hasText: /^Gender \*$/ }).nth(1).click();
    await page.getByRole('option', { name: 'Male', exact: true }).click();
    await page.getByRole('combobox', { name: 'specialities' }).click();
    await page.getByRole('option', { name: 'Chiropractic' }).click();
    await page.getByRole('combobox', { name: 'Role *' }).click();
    await page.getByRole('option', { name: 'Provider' }).click();
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('textbox', { name: 'Email *' }).click();
    await page.getByRole('textbox', { name: 'Email *' }).fill('samruddhii+1234@gmail.com');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('tab', { name: 'Scheduling' }).click();
    await page.locator('#menu-appbar div').first().click();
    await page.locator('#menu-appbar div').first().click();
    await page.getByRole('tab', { name: 'Scheduling' }).click();
    await page.locator('#menu-appbar div').first().click();
    await page.locator('#menu-appbar div').first().click();
    await page.getByRole('option', { name: 'leonardo patel' }).click();
    await page.getByRole('button', { name: 'Open' }).nth(1).click();
    await page.getByRole('option', { name: 'Telehealth' }).click();
    await page.getByRole('button', { name: 'Edit Availability' }).click();
    await page.getByRole('checkbox', { name: 'Set to Weekdays' }).check();
    await page.locator('form').filter({ hasText: 'Start Time *Start Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '08:00 AM' }).click();
    await page.locator('form').filter({ hasText: 'End Time *End Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: ':00 PM (9 hrs)' }).click();
    await page.getByRole('checkbox', { name: 'Telehealth' }).check();
    await page.getByRole('tab', { name: 'Tuesday' }).click();
    await page.locator('form').filter({ hasText: 'Start Time *Start Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '05:15 AM' }).click();
    await page.locator('form').filter({ hasText: 'End Time *End Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: ':00 PM (9 hrs 45 mins)' }).click();
    await page.getByRole('checkbox', { name: 'Telehealth' }).check();
    await page.getByRole('tab', { name: 'Wednesday' }).click();
    await page.locator('form').filter({ hasText: 'Start Time *Start Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '04:00 AM' }).click();
    await page.locator('form').filter({ hasText: 'End Time *End Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: ':30 PM (11 hrs 30 mins)' }).click();
    await page.getByRole('checkbox', { name: 'Telehealth' }).check();
    await page.getByRole('tab', { name: 'Thursday' }).click();
    await page.locator('form').filter({ hasText: 'Start Time *Start Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '07:15 AM' }).click();
    await page.locator('form').filter({ hasText: 'End Time *End Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: ':30 PM (13 hrs 15 mins)' }).click();
    await page.getByRole('checkbox', { name: 'Telehealth' }).check();
    await page.getByText('SundayMondayTuesdayWednesdayThursdayFridaySaturday').click();
    await page.getByRole('tab', { name: 'Friday' }).click();
    await page.locator('form').filter({ hasText: 'Start Time *Start Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '09:00 AM' }).click();
    await page.locator('form').filter({ hasText: 'End Time *End Time *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: ':30 PM (10 hrs 30 mins)' }).click();
    await page.getByRole('checkbox', { name: 'Telehealth' }).check();
    await page.locator('form').filter({ hasText: 'Appointment TypeAppointment' }).getByLabel('Open').click();
    await page.getByRole('option', { name: 'New Patient Visit' }).click();
    await page.locator('form').filter({ hasText: 'DurationDuration' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '75 minutes' }).click();
    await page.locator('form').filter({ hasText: 'Schedule NoticeSchedule Notice' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '12 Hours Away' }).click();
    await page.locator('form').filter({ hasText: 'Time Zone *Time Zone *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: 'Indian Standard Time (UTC +5:' }).click();
    await page.locator('form').filter({ hasText: 'Booking Window *Booking' }).getByLabel('Open').click();
    await page.getByRole('option', { name: '6 Week', exact: true }).click();
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('banner').getByTestId('ExpandMoreIcon').click();
    await page.getByText('New Appointment').click();
    await page.locator('form').filter({ hasText: 'Patient Name *Patient Name *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: 'leo john 24 Jul' }).click();
    await page.getByRole('combobox', { name: 'Appointment Type *' }).click();
    await page.getByRole('option', { name: 'New Patient Visit' }).click();
    await page.getByRole('textbox', { name: 'Reason For Visit *' }).click();
    await page.getByRole('textbox', { name: 'Reason For Visit *' }).fill('fever');
    await page.getByRole('button', { name: 'Telehealth' }).click();
    await page.locator('form').filter({ hasText: 'Provider *Provider *' }).getByLabel('Open').click();
    await page.getByRole('option', { name: 'leonardo patel' }).click();
    await page.getByRole('button', { name: 'View availability' }).click();
    await page.getByRole('gridcell', { name: '26' }).click();
    await page.getByRole('button', { name: ':00 AM - 10:15 AM' }).click();
    await page.getByRole('button', { name: 'Save And Close' }).click();
});